<?php

// Commission brief text template (FR-6.2). Key structure must match lang/zh_TW/commission.php exactly.
// Assembled by App\Services\CommissionBrief; palette hex values and credits are raw data and never rewritten.

return [
    'title' => '[Commission Brief] :name',
    'title_species' => '[Commission Brief] :name (:species)',
    'generated_by' => 'Generated by @:pawfit_id via Pawfit · :date',
    'kit_link' => 'Brief link (full-size references): :url',
    'share_link' => 'Full character sheet: :url',

    'section_character' => '■ Character',
    'name' => 'Name: :name',
    'species' => 'Species: :species',
    'tags' => 'Traits: :tags',
    'bio' => 'About:',

    'section_palette' => '■ Palette (hex codes are authoritative)',
    'palette_item' => ':index. :name :hex',
    'palette_item_note' => ':index. :name :hex (:note)',
    'palette_unnamed' => 'Color :index',
    'palette_empty' => '(no palette set yet)',

    'section_references' => '■ References (:count images, full size at the brief link)',
    'reference_item' => ':index. :caption',
    'reference_item_credit' => ':index. :caption — art by :credit',
    'reference_untitled' => 'Reference :index',
    'reference_nsfw' => '(NSFW)',

    'section_request' => '■ This commission',
    'request_fields' => [
        'composition' => 'Composition / pose',
        'scene' => 'Scene / background',
        'size' => 'Size / format',
        'usage' => 'Intended use',
        'budget' => 'Budget',
        'deadline' => 'Deadline',
        'notes' => 'Notes',
    ],
    'request_empty' => '(details to be confirmed with the commissioner)',

    'footer' => '— Compiled automatically by Pawfit from the character profile. Palette and artist credits are raw data; no AI image generation was used.',
];
